"""Draft the judge calibration file: one real /chat answer per golden question.

    python scripts/calibration_draft.py [--out data/golden/judgements.yaml]

Runs every question in data/golden/chat.yaml through the live chat pipeline
and writes the question, the answer and the rendered sources into the file
`joblens calibrate` reads, with the two human scores left empty. A reviewer
then fills in faithfulness and completeness (0-2 each) by reading the answer
against the sources, and `python -m joblens calibrate` reports how often the
LLM judge agrees with those scores.

The answers are produced by whatever LLM_BACKEND is configured, so the
calibration measures the judge on the answers the system actually gives.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from joblens import db
from joblens.eval import generation
from joblens.rag import chat as chat_rag
from joblens.search.embeddings import get_embedder

DEFAULT_OUT = (
    Path(__file__).resolve().parents[1] / "data" / "golden" / "judgements.yaml"
)

HEADER = """\
# Judge calibration set. Every entry is a real answer from /chat, with the
# sources it was given, scored by a reviewer on the same two scales the LLM
# judge uses (prompts/judge_answer): faithfulness and completeness, 0 to 2.
# `python -m joblens calibrate` re-scores each answer with the judge and
# reports agreement and Cohen's kappa against the scores here.
#
# Answers were generated by scripts/calibration_draft.py; the scores and
# notes were filled in by hand afterwards. Nothing here is used to gate CI
# until the kappa is worth quoting.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--limit", type=int, default=6, help="sources per answer")
    args = parser.parse_args(argv)

    cases = generation.load_cases()
    embedder = get_embedder()
    embedder.encode(["warm up"])
    scored = []
    with db.connect() as conn:
        for i, case in enumerate(cases, start=1):
            answer = chat_rag.ask(
                conn, case.question, embedder=embedder, limit=args.limit
            )
            scored.append(
                {
                    "id": case.id,
                    "question": case.question,
                    "answer": answer.answer,
                    "sources": "\n\n".join(s.render() for s in answer.sources),
                    "cited": sorted(answer.cited),
                    "must_refuse": case.must_refuse,
                    "faithfulness": None,
                    "completeness": None,
                    "note": "",
                }
            )
            print(f"{i}/{len(cases)} {case.id} {answer.took_ms}ms", flush=True)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        {"version": 1, "scored": scored},
        sort_keys=False,
        width=88,
        allow_unicode=True,
    )
    args.out.write_text(HEADER + body, encoding="utf-8")
    print(f"wrote {len(scored)} answers to {args.out}; fill in the scores")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
