"""Export the Indian company list from the EasyJobs seed file.

    python scripts/export_easyjobs_companies.py
    python scripts/export_easyjobs_companies.py --seed path/to/seed-companies.ts

Writes data/companies_in.yaml: one entry per company whose careers page runs
on Greenhouse, Lever or Ashby, the three boards with an official public job
API that needs no key. The list was curated and slug-checked against the live
APIs in the EasyJobs project; this script only carries it across, so the
origin of every company in the corpus is reproducible.

Keka and Workable companies are left out on purpose. Keka has no documented
public API, and Workable is a later addition.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SEED = ROOT.parent / "EasyJobs" / "data" / "seed-companies.ts"
OUTPUT = ROOT / "data" / "companies_in.yaml"
PROVIDERS = ("greenhouse", "lever", "ashby")

# Every seed entry is a one-line object literal, so a field is `key: "value"`
# on the same line. Values never contain an unescaped double quote.
ENTRY = re.compile(r"^\s*\{\s*name:")
FIELD = r'\b{key}:\s*"((?:[^"\\]|\\.)*)"'


def _field(line: str, key: str) -> str | None:
    match = re.search(FIELD.format(key=key), line)
    return match.group(1).replace('\\"', '"') if match else None


def parse(seed_text: str) -> list[dict]:
    companies = []
    for line in seed_text.splitlines():
        if not ENTRY.match(line):
            continue
        provider = _field(line, "atsProvider")
        if provider not in PROVIDERS:
            continue
        companies.append(
            {
                "name": _field(line, "name"),
                "provider": provider,
                "slug": _field(line, "atsSlug"),
                "city": _field(line, "city"),
            }
        )
    return companies


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--seed", type=Path, default=DEFAULT_SEED)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    companies = parse(args.seed.read_text(encoding="utf-8"))
    missing = [c for c in companies if not all(c.values())]
    if missing:
        print(f"entries with a missing field: {missing}", file=sys.stderr)
        return 1
    seen: set[tuple[str, str]] = set()
    for company in companies:
        key = (company["provider"], company["slug"].lower())
        if key in seen:
            print(f"duplicate board: {key}", file=sys.stderr)
            return 1
        seen.add(key)

    header = (
        "# Indian companies with a public Greenhouse, Lever or Ashby job board.\n"
        "# Generated by scripts/export_easyjobs_companies.py from the EasyJobs\n"
        "# seed list (data/seed-companies.ts). Edit the seed, not this file.\n"
    )
    body = yaml.safe_dump(companies, sort_keys=False, allow_unicode=True)
    args.output.write_text(header + body, encoding="utf-8", newline="\n")
    counts = {p: sum(c["provider"] == p for c in companies) for p in PROVIDERS}
    print(f"wrote {len(companies)} companies to {args.output}: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
